function withValidProperties(
  properties: Record<string, undefined | string | string[]>,
) {
  return Object.fromEntries(
    Object.entries(properties).filter(([_, value]) =>
      Array.isArray(value) ? value.length > 0 : !!value,
    ),
  );
}

export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL || "https://gigipay-app.vercel.app";

  const manifest = {
    accountAssociation: {
      header:
        "eyJmaWQiOjEzMTIyNDAsInR5cGUiOiJhdXRoIiwia2V5IjoiMHgxMzIyZjVkNWJkZDA4MTdDNDc2RkNlNDg0OTkxODdiMDlFNjAxNjQ2In0",
      payload: "eyJkb21haW4iOiJnaWdpcGF5LWFwcC52ZXJjZWwuYXBwIn0",
      signature:
        "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAAAAAAAAAAAAAC6XtEQ79uj0AW_yILXU1isu7hYQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVD_7o28AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECmyyEpXoDxQ-1Q0RARguCYHMQJSmFflpQz1JthsJGNxTOQDRaxdjmPwj_Mnjw6cktr1fOKnZmZfWcf4WwehibJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAD4UhCyHMUDAvR3ulZobSAZ3JtnreFbCoxE7K1FZTPQEQ6tLOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABf8TfUsP3NSdyjDHz1fleKAm0niQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFxB-tlIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAABMi9dW90IF8R2_OSEmRh7CeYBZGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAABMi9dW90IF8R2_OSEmRh7CeYBZGAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABW7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAax2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADELCq9HgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkDw8_JAAAAAAAAAAAAAAAAII8ls7FXpnn8SA3xuftGPzUkJKTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDY_RxbfAYOzs-_vkIB7aVIcW8-wQuo7-HoRFWNQQeagSwvbIsJzzb27inx5uNMO5VgQEtLw6h2g78jmCZnPcxgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoicHJBQ0Fxc0RDa3VocE9yRVgtZmIwU05zOGs3S1hiaVZLY0VxNkZPUHFEdyIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFd-hCkIIob3GCEQbFobg4sHe8bDc-nNfy8jH-jhXHpC2WdYbctQDdkQrc0lG0dPN8tEQTd01FQXbErby_X2ABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACXxmAhrLbFyVnMbxFZnO5a87yP1HR-6zdfEN572VGVXLx0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIp7InR5cGUiOiJ3ZWJhdXRobi5nZXQiLCJjaGFsbGVuZ2UiOiJIRVVGcmh4d00tSGl1OG9URzZQa1NLZ0J3Q3VQdWVKTlJJbXZkQ005d0ZFIiwib3JpZ2luIjoiaHR0cHM6Ly9rZXlzLmNvaW5iYXNlLmNvbSIsImNyb3NzT3JpZ2luIjpmYWxzZX0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI",
    },
    miniapp: withValidProperties({
      version: "1",
      name: "GigiPay",
      homeUrl: URL,
      iconUrl: `${URL}/icon.png`,
      imageUrl: `${URL}/icon.png`, // Required for Base App preview
      splashImageUrl: `${URL}/splash.png`,
      splashBackgroundColor: "#000000",
      webhookUrl: `${URL}/api/webhook`,
      subtitle: "Fast, cheap, inclusive payments",
      description:
        "GigiPay is a Celo-powered payment protocol designed to make on-chain transfers faster, cheaper, and more inclusive. Send funds to multiple wallets in a single transaction or use claim-code payments without needing recipient wallet addresses.",
      screenshotUrls: [
        // Add screenshot URLs when available
      ],
      primaryCategory: "finance",
      tags: ["payments", "celo", "base", "crypto", "web3"],
      heroImageUrl: `${URL}/splash.png`,
      tagline: "Pay anyone, anywhere, instantly",
      ogTitle: "GigiPay - Fast & Inclusive Crypto Payments",
      ogDescription:
        "Send crypto to multiple wallets or generate claim codes for payments without wallet addresses. Built on Celo and Base.",
      ogImageUrl: `${URL}/splash.png`,
      noindex: "true", // Set to "false" when ready for production
    }),
  };

  return Response.json(manifest);
}
